default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= ENV['DEV_PASSWORD'] %>
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: receta_development

test:
  <<: *default
  database: receta_test

production:
  <<: *default
  database: receta_production
